#!/bin/bash

configure_env_files() {
    read -rp "Enter your database URI (e.g. postgres://yourname:yourpassword@your-database.domain/path): " DATABASE_URI

    read -rp "Enter your AWS profile name (see https://github.com/Theodo-UK/OmniLog/blob/main/docs/aws_setup.md if you have not set this up): " AWS_PROFILE_NAME
    read -rp "Enter the AWS region you would like to deploy to (e.g. eu-west-2): " AWS_REGION
    read -rp "Enter a name to identify omnilog resources on your AWS (default: omnilog): " SST_STAGE_NAME
    SST_STAGE_NAME=${SST_STAGE_NAME:-omnilog} # set SST_STAGE_NAME to omnilog if unset or empty
    read -rp "Enter NEXTAUTH_SECRET (default: generated by openssl rand -hex 32): " NEXTAUTH_SECRET
    NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-$(openssl rand -hex 32)} # generate and set NEXTAUTH_SECRET if user does not provide secret

    # Create .env files
    create_env_file ".env" "$DATABASE_URI"
    create_env_file ".env.development" "$DATABASE_URI" "$AWS_PROFILE_NAME" "$AWS_REGION" "$SST_STAGE_NAME"
    create_env_file ".env.production" "$DATABASE_URI" "$AWS_PROFILE_NAME" "$AWS_REGION" "$SST_STAGE_NAME" "$NEXTAUTH_SECRET"
}